name: bly
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.12.12=py312hd8ed1ab_1
  - debugpy=1.8.17=py312h56d30c9_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - libblas=3.11.0=2_h51639a9_openblas
  - libcblas=3.11.0=2_hb0561ab_openblas
  - libcxx=21.1.6=hf598326_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libgcc=15.2.0=hcbb3090_13
  - libgfortran=15.2.0=h07b0088_13
  - libgfortran5=15.2.0=hdae7583_13
  - liblapack=3.11.0=2_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libopenblas=0.3.30=openmp_ha158390_3
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.0=h8adb53f_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.6=h4a912ad_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.3.5=py312h85ea64e_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - polars=1.35.2=pyh6a1acc5_0
  - polars-runtime-32=1.35.2=py310h34bb384_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py312h37e1c23_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.12.12=h18782d2_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.12=hd8ed1ab_1
  - python_abi=3.12=8_cp312
  - pyzmq=27.1.0=py312hd65ceae_0
  - readline=8.2=h1d1bf99_2
  - scikit-learn=1.7.2=py312h79e0ffc_0
  - scipy=1.16.3=py312ha6bbf71_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_3
  - tornado=6.5.2=py312h4409184_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - pip:
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - blyjections==0.0.1
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - datetime==6.0
      - dotenv==0.9.9
      - fonttools==4.60.1
      - idna==3.11
      - kiwisolver==1.4.9
      - lxml==6.0.2
      - matplotlib==3.10.7
      - pandas==2.3.3
      - pillow==12.0.0
      - pyarrow==22.0.0
      - pybaseball==2.2.7
      - pycparser==2.23
      - pygithub==2.8.1
      - pyjwt==2.10.1
      - pynacl==1.6.1
      - pyparsing==3.2.5
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - soupsieve==2.8
      - tqdm==4.67.1
      - typing==3.7.4.3
      - tzdata==2025.2
      - urllib3==2.5.0
      - zope-interface==8.1.1
prefix: /opt/miniconda3/envs/bly
