max_season: 2025
min_season: 2015
seasons:
#  2013:
#    start_date: '2013-03-29'
#    end_date: '2013-09-29'
#  2014:
#    start_date: '2014-03-22'
#    end_date: '2014-09-28'
  2015:
    start_date: '2015-04-05'
    end_date: '2015-10-04'
  2016:
    start_date: '2016-04-03'
    end_date: '2016-10-02'
  2017:
    start_date: '2017-04-02'
    end_date: '2017-10-01'
  2018:
    start_date: '2018-03-29'
    end_date: '2018-09-30'
  2019:
    start_date: '2019-03-28'
    end_date: '2019-09-29'
  2020:
    start_date: '2020-07-23'
    end_date: '2020-09-27'
  2021:
    start_date: '2021-04-01'
    end_date: '2021-10-04'
  2022:
    start_date: '2022-04-07'
    end_date: '2022-10-05'
  2023:
    start_date: '2023-03-30'
    end_date: '2023-10-02'
  2024:
    start_date: '2024-03-20'
    end_date: '2024-09-30'
  2025:
    start_date: '2025-03-18'
    end_date: '2025-09-28'
  2026:
    start_date: '2026-03-25'
    end_date: '2026-09-27'
batting_basic:
    - Season
    - IDfg
    - Name
    - Age
    - G
    - PA
    - AB
    - H
    - 1B
    - 2B
    - 3B
    - HR
    - R
    - RBI
    - BB
    - IBB
    - HBP
    - SO
    - SB
    - CS
    - GDP
